name: flake-ardupilot
on:
  push:
    branches: [main, ci-test]
  pull_request:

jobs:
    sitl-bc:
        runs-on: ubuntu-24.04
        steps:
            - uses: actions/checkout@v4
            - uses: cachix/install-nix-action@v31
              with:
                github_access_token: ${{ secrets.GITHUB_TOKEN }}
            - uses: cachix/cachix-action@v15
              with:
                name: galois
            - run: nix build .#sitl_bc
            - uses: actions/upload-artifact@v4
              with:
                if-no-files-found: error
                path: result/c3pyl35n1ndm15jw39ga1lw3n2gb7l1q-ardupilot-sitl-bc-bc/bin
                name: ardupilot-sitl-bitcode
